version: "3.8"
services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5430:5430
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
